""" 

Primeiro exemplo dos codigos do Google Colaboratory testados em sala de aula do dia 16/02/2024

Automatically generated by Colaboratory.

Original file is located at: 
    https://colab.research.google.com/drive/1E7ppwKPORhJbRboaj5X2wEgWWs7tqJEd

"""

soma = 0
n=10
for i in range(n + 1):
    soma = soma + i
print(soma)
