""" 

Primeiro exemplo dos codigos do Google Colaboratory testados em sala de aula do dia 16/02/2024

Automatically generated by Colaboratory.

Original file is located at: 
    https://colab.research.google.com/drive/1E7ppwKPORhJbRboaj5X2wEgWWs7tqJEd

"""

soma = 0    # Cria a variavel 'soma' e deixa vazia
n=10        # Cria a variavel 'n' com o valor de 10

for i in range(n + 1):      # Cria um loop com 'for' onde adiciona os valore de n + 1 ao 'i'
    soma = soma + i # Define que a variavel 'soma' será o 'i' + a variavel 'soma'

print(soma)     # Imprime o valor final de soma

# FIM!